# Generated by Django 4.2 on 2023-06-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
