# Generated by Django 4.2 on 2023-08-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_departments_image_departments_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='specialisation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
