# Generated by Django 4.2 on 2023-09-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=100)),
                ('doctorid', models.CharField(max_length=30)),
                ('password', models.CharField(default='12345678', max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField(default=1)),
                ('image', models.ImageField(upload_to='doctor')),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_app.departments')),
            ],
            options={
                'db_table': 'doctor_tb',
            },
        ),
    ]
