# Generated by Django 4.2 on 2023-08-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='mobile',
            field=models.BigIntegerField(default=1),
        ),
    ]
