# Generated by Django 4.2 on 2023-09-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
