# Generated by Django 4.2 on 2023-08-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0006_alter_departments_specialisation'),
        ('doctor', '0003_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('date_of_appoinment', models.DateField()),
                ('report', models.CharField(default='none', max_length=100)),
                ('medicine', models.CharField(default='none', max_length=100)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.departments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'db_table': 'patient_tb',
            },
        ),
    ]
