# Generated by Django 4.2 on 2023-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital_app', '0002_patient_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slotTime',
            field=models.CharField(default='', max_length=10),
        ),
    ]
