# Generated by Django 4.2 on 2023-09-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('patient', '0001_initial'),
        ('doctor', '0002_doctor_address'),
        ('myhospital_app', '0004_remove_patient_department_remove_patient_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('slotTime', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.departments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.slots')),
            ],
            options={
                'db_table': 'booking_tb',
            },
        ),
    ]
