# Generated by Django 4.2 on 2023-09-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital_app', '0006_remove_patient_medicine_remove_patient_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='12345678', max_length=10),
        ),
    ]
