# Generated by Django 4.2 on 2023-09-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital_app', '0007_alter_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='booking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myhospital_app.booking'),
        ),
    ]
