# Generated by Django 4.2 on 2023-09-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital_app', '0008_alter_patient_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhospital_app.booking'),
        ),
    ]
