# Generated by Django 4.2 on 2023-09-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital_app', '0009_alter_patient_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhospital_app.patient'),
        ),
    ]
