# Generated by Django 4.2 on 2023-09-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital_app', '0010_remove_patient_booking_booking_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
