# Generated by Django 4.2 on 2023-09-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital_app', '0012_prescription'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prescription',
            table='prescription_tb',
        ),
    ]
